package qveex.ru.more.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3E58B1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001550)
val md_theme_light_secondary = Color(0xFF2751D8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001452)
val md_theme_light_tertiary = Color(0xFF006398)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D31)
val md_theme_light_error = Color(0xFFBE0A18)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB6C4FF)
val md_theme_light_surfaceTint = Color(0xFF3E58B1)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFBF8FD)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)

val md_theme_dark_primary = Color(0xFFB6C4FF)
val md_theme_dark_onPrimary = Color(0xFF00277F)
val md_theme_dark_primaryContainer = Color(0xFF234098)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val md_theme_dark_secondary = Color(0xFFB7C4FF)
val md_theme_dark_onSecondary = Color(0xFF002583)
val md_theme_dark_secondaryContainer = Color(0xFF0038B7)
val md_theme_dark_onSecondaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_tertiary = Color(0xFF93CCFF)
val md_theme_dark_onTertiary = Color(0xFF003351)
val md_theme_dark_tertiaryContainer = Color(0xFF004B73)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_error = Color(0xFFFFB4AC)
val md_theme_dark_errorContainer = Color(0xFF93000E)
val md_theme_dark_onError = Color(0xFF690007)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inversePrimary = Color(0xFF3E58B1)
val md_theme_dark_surfaceTint = Color(0xFFB6C4FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF131316)
val md_theme_dark_onSurface = Color(0xFFC8C6CA)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)

val successColor = Color(0xD828C500)
val errorColor = Color(0xD8CE0000)

val seed = Color(0xFF002882)